#Config file to configure the pis
#""
[DEFAULT]
IP=
;IP=127.0.0.1
;IP=localhost
; IP=IP=0.0.0.0
ROLE=
;ROLE2=Receiver
# 0 = 128 BIT security LVL : 1 = 244 BIT security LVL
SECPARAM=1
JSONDIR=../results244/cache
;JSONDIR=../results128/cache
